language: node_js
sudo: false
node_js:
  - '4.1.2'

addons:
  postgresql: "9.3"

before_install:
  - npm config set ca ""

before_script:
  - psql -c 'create database livesnooker_test;' -U postgres
  - ./grunt.sh copy:ci

services:
  - redis-server
